### ISSUE TITLE
Handle multiple fonts in `src/fonts`

### ISSUE THREAD

**Issue by RoelN** [kabisa/specimen-skeleton#24]
- [x] Create JS data for FontFaceObserver so it will observe multiple fonts
- [x] Create stylesheet with multiple fonts
- [x] Split up CSS variables and font-family stuff (note to self: re-setting CSS variables on each elements is bad!)
- [x] Generate all elements in the side per font, instead of just once

## (Breaking) changes

- Font is not applied side-wide, but should be applied "locally" on elements by their classname

**Comment by davelab6** [comment]
I suggest to add a milestone with a date, and assign this, to show its going to be worked on

**Comment by RoelN** [comment]
Work started in https://github.com/kabisa/specimen-skeleton/pull/58 ✊

**Comment by RoelN** [comment]
Døn!
