### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by RoelN** [kabisa/specimen-skeleton#47]
This is the logo, so we can link to it. Eternal respect to [Guido Theelen](https://github.com/guidotheelen) for the logo!

![specimen-skeleton](https://user-images.githubusercontent.com/4570664/74531935-456bbd00-4f2e-11ea-9b9d-d1615bd2ef79.png)

**Comment by RoelN** [comment]
Resized and circleified:

![specimen-skeleton](https://user-images.githubusercontent.com/4570664/74532263-0db14500-4f2f-11ea-96e9-49bcb8699ebb.png)

**Comment by pascalw** [comment]
@RoelN this can be closed I think?

**Comment by RoelN** [comment]
Link seems to continue to work, so it's closin' time!
