### ISSUE TITLE
Use Flont for interactive previews?

### ISSUE THREAD

**Issue by davelab6** [kabisa/specimen-skeleton#52]
https://github.com/chrissam42/Flont ?

**Comment by RoelN** [comment]
Looks nice! Not a good fit for Specimen Skeleton though, as it uses Opentype.js to do in-browser analysis of a font. We explicitly do this offline, during build, to keep the site super tiny and responsive.

That said, we need some more controls for the type tester like Flont has! Issue [here](https://github.com/kabisa/specimen-skeleton/issues/53).
