### ISSUE TITLE
Group glyphs by type

### ISSUE THREAD

**Issue by davelab6** [kabisa/specimen-skeleton#57]
@markboulton suggested 

> The current glyph table dumps all characters sequentially; it would be better to group glyphs by type, as is often done in specimens.

@RoelN said,

> I had a quick look at grouping those characters by type. It looks like Unicode categories aren't directly usable. For instance, the "Currency Symbols"-block doesn't contain the `$`.
>
> The "Character Viewer" on Mac has a better categorisation, maybe we can tap into that and refine as needed
>
> Alternatively we can look at groupings in existing specimens. Some of that can be automated, but it'd be a mostly manual process. (I would be interested in such a list for Wakamai Fondue myself, by the way! Beats a "dumb character dump")

It seems to me that a good source of such glyph metadata, libre licensed, is https://github.com/schriftgestalt/GlyphsInfo/blob/master/GlyphData.xml which is fully documented at https://glyphsapp.com/tutorials/roll-your-own-glyph-data and there's a freeware macOS app https://glyphsapp.com/tools/editglyphdata for dealing with it, but its standards compliant XML so any editor can do :)

**Comment by markboulton** [comment]
Ok, digging out my PDF grouping research, this seems to be a list of common groupings across most of them.

- Uppercase latin
- Lowercase latin
- Additional languages (organised by language name) if supported (although, this varies hugely depending on the font)
- Standard punctuation
- All cap punctuation
- Proportional (default) figures
- Tabular figures
- Old style figures
- Prebuilt fractions
- Numerators & denominators
- Superscript & subscript
- Stylistic alternates
- Accented uppercase
- Accented lower case
- Arrows & Icons

**Comment by RoelN** [comment]
These are the categories used in the GlyphsData.xml. I see similarities, but it's a different list as these are all linked to Unicode values instead of typographic categories. Some of those categories aren't encoded in Unicode (e.g. tabular figures) as they are alternative glyphs for an existing character.

But maybe we can merge these lists so @markboulton's list has as many matching unicode characters as possible?

## GlyphsData.xml

- Separator
    - Space
    - Format
    - Nonspace
- Punctuation
    - Quote
    - Parenthesis
    - Dash
    - Spacing
    - Modifier
- Symbol
    - Currency
    - Math
    - Modifier
    - Superscript
    - Format
    - Ligature
    - Spacing
    - Arrow
    - Geometry
- Number
    - Decimal Digit
    - Small
    - Fraction
    - Spacing
    - Letter
- Letter
    - Uppercase
    - Lowercase
    - Superscript
    - Modifier
    - Ligature
    - Halfform
    - Matra
    - Spacing
    - Jamo
    - Syllable
    - Number
- Mark
    - Modifier
    - Spacing
    - Nonspacing
    - Enclosing
    - Spacing Combining
    - Ligature
- Other
    - Format

**Comment by RoelN** [comment]
I propose a list of categories and subcategories, each with a list of Unicode characters and optionally the layout feature to enable them. For instance:


```
figures:
	Prebuilt fractions:
		chars: ["½", "⅓", ... "⅞"]
		feature: -
	Proportional (default) figures
		chars: ["0", "1", ... "9"]
		feature: -
	Tabular figures
		chars: ["0", "1", ... "9"]
		feature: tnum
	Old style figures
		chars: ["0", "1", ... "9"]
		feature: onum
etc.
```

Something like this would be used by the skeleton to build a grid with all relevant glyphs/chars grouped.

**Comment by markboulton** [comment]
This looks like a good proposal to me, Roel.

**Comment by davelab6** [comment]
+1. That structure will also work better than just Unicode ranges for definition of language support in a basic way. The dictionary of characters should take ranges :)

**Comment by RoelN** [comment]
Fixed with https://github.com/kabisa/specimen-skeleton/pull/61 and https://github.com/kabisa/specimen-skeleton-support/pull/12

Categories and subcategories are now 100% based on the ones GlyphData.xml. This could be remapped to different categories by the author in a SS template.
