### ISSUE TITLE
Easier access to, and more control of font data

### ISSUE THREAD

**Issue by RoelN** [kabisa/specimen-skeleton#64]
Accessing multiple fonts is cumbersome in the current setup. Also, order of fonts is not guaranteed because of the nondeterministic way 11ty processes _data files:

> The non deterministic order seems to be caused by 11ty. 11ty adds global data files to the global data file in an non-deterministic order. Even if it didn't, relying on ordering of object keys is not very safe. So best is probably to generate a list of fonts somewhere, where we control the order of that list.

@pascalw proposes this:

Generate `src/fonts/meta.json` and fill it:

```json
{
  "fonts": [
    {
       "name": "font one",
       "selector": "font-one"
    },
    {
       "name": "font two",
       "selector": "font-two"
    },
  ]
}
```

Then we can avoid generating `fonts.js`, as this JSON can directly imported instead via Webpack, giving us access to the same data we need. An author can tweak the order of fonts by editing the `meta.json` file. We'd also be able to work with arrays instead of objects, further simplifying things.

**Comment by markboulton** [comment]
This approach makes a lot of sense for me from an authoring perspective.

**Comment by RoelN** [comment]
`yarn fontdata` now produces a metafile in which you can change the order or even append custom variables.
